---
title: 'plot_for_balance'
description: 'Generate forest plot specimen map and collection balance'
toc: true
toc-depth: 3
---


```{r}
#| eval: false
forplotR::plot_for_balance()
```

### Description

Processes field data collected using the [Forestplots format](https://forestplots.net/)
and generates a specimen map (2D plot) with collection status and spatial
distribution of individuals across subplots. Generate a PDF with a full plot
report with separate maps, for each subplot and a spreadsheet summarizing the
percentage of collected specimens per subplot. The function performs the
following steps: (i) validates all input arguments and checks/create output
folders; (ii) reads the Forestplots-formatted xlsx sheet, extracts metadata
(team, plot name, plot code), and cleans the data; (iii) normalizes and cleans
coordinate and diameter values, computing global plot coordinates from
subplot-relative positions; (iv) creates a PDF report, including plot metadata,
the main map, collected and uncollected specimen maps, optionally a map
highlighting palms (Arecaceae) and navigable individual subplot  maps; (v)
optionally generates a xlsx spreadsheet with the collection
percentage per subplot (including totals), distinguishing collected vs.
uncollected, and palm individuals.

### Arguments

| Argument | Description |
|---|---|
| fp_file_path | File path to the forestplots dataset (Excel format). |
| plot_size | Overall plot size in hectares (default is 1 ha). |
| subplot_size | Side length of subplots in meters (default is 10 m). |
| highlight_palms | Logical. If TRUE, highlights Arecaceae in purple. |
| dir | Directory path where output will be saved (default is "Results_map_plot"). |
| filename | Name of the output file for the main plot (without extension). |

### Value

A PDF report and a summary Excel file with collection statistics.

### Examples

```r
plot_for_balance(fp_file_path = "data/forestplot.xlsx",
                 plot_size = 1,
                 subplot_size = 10,
                 highlight_palms = TRUE,
                 dir = "Results_map_plot",
                 filename = "plot_specimen")
```


